"""
Notebook Writer Skill
=====================
Generate and modify Jupyter notebook cells for DILI experiments.

USER-CONTROLLED: Only the user can modify this skill.

IMPORTANT: This is the ONLY skill that modifies the experiment notebook.
"""

import json
import nbformat
from pathlib import Path
from typing import Dict, List, Optional, Any
from datetime import datetime

# Import skill registry
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from agent.base_agent import skills

# ============================================================================
# NOTEBOOK CONFIGURATION
# ============================================================================

NOTEBOOK_PATH = Path(__file__).parent.parent / "experiments" / "dili_optimization.ipynb"

DEFAULT_NOTEBOOK = {
    "cells": [],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        },
        "dili_agent": {
            "created": "",
            "last_modified": "",
            "iterations": 0
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}


# ============================================================================
# SKILL FUNCTIONS
# ============================================================================

@skills.register("read_notebook", "Read current notebook state")
def read_notebook(
    notebook_path: str = None
) -> Dict[str, Any]:
    """
    Read the current state of the experiment notebook.

    Args:
        notebook_path: Path to notebook (default: experiments/dili_optimization.ipynb)

    Returns:
        Notebook structure and cell summaries
    """
    path = Path(notebook_path) if notebook_path else NOTEBOOK_PATH

    if not path.exists():
        return {
            "status": "not_found",
            "message": f"Notebook not found at {path}",
            "exists": False
        }

    try:
        with open(path, 'r') as f:
            nb = nbformat.read(f, as_version=4)

        cells_summary = []
        for i, cell in enumerate(nb.cells):
            summary = {
                "index": i,
                "type": cell.cell_type,
                "lines": len(cell.source.split('\n')),
                "preview": cell.source[:100] + "..." if len(cell.source) > 100 else cell.source
            }
            if cell.cell_type == "code" and hasattr(cell, 'outputs'):
                summary["has_output"] = len(cell.outputs) > 0
            cells_summary.append(summary)

        return {
            "status": "success",
            "exists": True,
            "n_cells": len(nb.cells),
            "cells": cells_summary,
            "metadata": nb.metadata.get("dili_agent", {})
        }

    except Exception as e:
        return {"status": "error", "message": str(e)}


@skills.register("create_notebook", "Create a new experiment notebook")
def create_notebook(
    notebook_path: str = None,
    title: str = "DILI Optimization Experiment"
) -> Dict[str, Any]:
    """
    Create a new experiment notebook with default structure.

    Args:
        notebook_path: Path for new notebook
        title: Notebook title

    Returns:
        Creation status
    """
    path = Path(notebook_path) if notebook_path else NOTEBOOK_PATH

    # Ensure directory exists
    path.parent.mkdir(parents=True, exist_ok=True)

    # Create notebook structure
    nb = nbformat.v4.new_notebook()
    nb.metadata["dili_agent"] = {
        "created": datetime.now().isoformat(),
        "last_modified": datetime.now().isoformat(),
        "iterations": 0
    }

    # Add header cells
    header_md = f"""# {title}

**Generated by DILI Optimization Agent**

Created: {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Objective
Optimize ML workflow for Drug-Induced Liver Injury (DILI) prediction.

## Approach
- Feature engineering: Fingerprints, descriptors, bioactivity data
- Model optimization: Multiple classifiers with hyperparameter tuning
- Evaluation: Cross-validation with MCC as primary metric
"""

    imports_code = """# Core imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# ML imports
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import matthews_corrcoef, roc_auc_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

# RDKit for molecular features
try:
    from rdkit import Chem
    from rdkit.Chem import AllChem, Descriptors
    RDKIT_AVAILABLE = True
except ImportError:
    RDKIT_AVAILABLE = False
    print("RDKit not available - install with: pip install rdkit")

# Set random seed for reproducibility
np.random.seed(42)

print("Imports complete")
"""

    nb.cells.append(nbformat.v4.new_markdown_cell(header_md))
    nb.cells.append(nbformat.v4.new_code_cell(imports_code))

    try:
        with open(path, 'w') as f:
            nbformat.write(nb, f)

        return {
            "status": "success",
            "path": str(path),
            "n_cells": len(nb.cells)
        }

    except Exception as e:
        return {"status": "error", "message": str(e)}


@skills.register("add_cell", "Add a cell to the notebook")
def add_cell(
    content: str,
    cell_type: str = "code",
    position: int = -1,
    notebook_path: str = None
) -> Dict[str, Any]:
    """
    Add a new cell to the experiment notebook.

    Args:
        content: Cell content (code or markdown)
        cell_type: 'code' or 'markdown'
        position: Position to insert (-1 = end)
        notebook_path: Path to notebook

    Returns:
        Updated notebook info
    """
    path = Path(notebook_path) if notebook_path else NOTEBOOK_PATH

    if not path.exists():
        # Create notebook if it doesn't exist
        create_result = create_notebook(str(path))
        if create_result["status"] != "success":
            return create_result

    try:
        with open(path, 'r') as f:
            nb = nbformat.read(f, as_version=4)

        # Create new cell
        if cell_type == "code":
            new_cell = nbformat.v4.new_code_cell(content)
        else:
            new_cell = nbformat.v4.new_markdown_cell(content)

        # Insert at position
        if position < 0 or position >= len(nb.cells):
            nb.cells.append(new_cell)
            actual_position = len(nb.cells) - 1
        else:
            nb.cells.insert(position, new_cell)
            actual_position = position

        # Update metadata
        nb.metadata["dili_agent"]["last_modified"] = datetime.now().isoformat()
        nb.metadata["dili_agent"]["iterations"] = nb.metadata["dili_agent"].get("iterations", 0) + 1

        with open(path, 'w') as f:
            nbformat.write(nb, f)

        return {
            "status": "success",
            "cell_position": actual_position,
            "cell_type": cell_type,
            "n_cells": len(nb.cells)
        }

    except Exception as e:
        return {"status": "error", "message": str(e)}


@skills.register("update_cell", "Update an existing cell")
def update_cell(
    cell_index: int,
    new_content: str,
    notebook_path: str = None
) -> Dict[str, Any]:
    """
    Update content of an existing cell.

    Args:
        cell_index: Index of cell to update
        new_content: New cell content
        notebook_path: Path to notebook

    Returns:
        Update status
    """
    path = Path(notebook_path) if notebook_path else NOTEBOOK_PATH

    if not path.exists():
        return {"status": "error", "message": "Notebook not found"}

    try:
        with open(path, 'r') as f:
            nb = nbformat.read(f, as_version=4)

        if cell_index < 0 or cell_index >= len(nb.cells):
            return {"status": "error", "message": f"Invalid cell index: {cell_index}"}

        nb.cells[cell_index].source = new_content
        nb.metadata["dili_agent"]["last_modified"] = datetime.now().isoformat()

        with open(path, 'w') as f:
            nbformat.write(nb, f)

        return {
            "status": "success",
            "cell_index": cell_index,
            "cell_type": nb.cells[cell_index].cell_type
        }

    except Exception as e:
        return {"status": "error", "message": str(e)}


@skills.register("add_experiment_section", "Add a complete experiment section")
def add_experiment_section(
    section_name: str,
    description: str,
    code_blocks: List[str],
    notebook_path: str = None
) -> Dict[str, Any]:
    """
    Add a complete experiment section with header and code.

    Args:
        section_name: Section title
        description: Section description
        code_blocks: List of code cell contents
        notebook_path: Path to notebook

    Returns:
        Section addition status
    """
    path = Path(notebook_path) if notebook_path else NOTEBOOK_PATH

    # Add markdown header
    header_md = f"""## {section_name}

{description}

*Added: {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""

    results = []

    # Add header
    result = add_cell(header_md, cell_type="markdown", notebook_path=str(path))
    results.append(result)

    # Add code blocks
    for code in code_blocks:
        result = add_cell(code, cell_type="code", notebook_path=str(path))
        results.append(result)

    success_count = sum(1 for r in results if r.get("status") == "success")

    return {
        "status": "success" if success_count == len(results) else "partial",
        "section_name": section_name,
        "cells_added": success_count,
        "total_attempted": len(results)
    }


@skills.register("generate_data_loading_code", "Generate code for loading data")
def generate_data_loading_code(
    data_path: str,
    smiles_column: str = "SMILES",
    label_column: str = "DILI_label"
) -> str:
    """
    Generate code for loading and preprocessing DILI data.

    Args:
        data_path: Path to data file
        smiles_column: Name of SMILES column
        label_column: Name of label column

    Returns:
        Python code string
    """
    code = f'''# Load DILI dataset
data_path = "{data_path}"

if data_path.endswith('.xlsx') or data_path.endswith('.xls'):
    df = pd.read_excel(data_path)
else:
    df = pd.read_csv(data_path)

print(f"Loaded {{len(df)}} compounds")
print(f"Columns: {{list(df.columns)}}")

# Extract SMILES and labels
smiles_col = "{smiles_column}"
label_col = "{label_column}"

# Check columns exist
assert smiles_col in df.columns, f"SMILES column '{{smiles_col}}' not found"

# Display data distribution
if label_col in df.columns:
    print(f"\\nLabel distribution:")
    print(df[label_col].value_counts())
else:
    print(f"Note: Label column '{{label_col}}' not found - will need to create")

df.head()
'''
    return code


@skills.register("generate_feature_code", "Generate feature engineering code")
def generate_feature_code(
    feature_type: str = "morgan",
    **kwargs
) -> str:
    """
    Generate code for feature engineering.

    Args:
        feature_type: Type of features (morgan, maccs, rdkit_2d)

    Returns:
        Python code string
    """
    if feature_type == "morgan":
        code = f'''# Generate Morgan fingerprints
from rdkit import Chem
from rdkit.Chem import AllChem

def smiles_to_morgan(smiles, radius=2, n_bits=2048):
    """Convert SMILES to Morgan fingerprint."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=n_bits)
    return np.array(fp)

# Apply to dataset
fingerprints = []
valid_idx = []

for i, smi in enumerate(df[smiles_col]):
    fp = smiles_to_morgan(smi)
    if fp is not None:
        fingerprints.append(fp)
        valid_idx.append(i)

X = np.array(fingerprints)
y = df.iloc[valid_idx][label_col].values

print(f"Generated fingerprints: {{X.shape}}")
print(f"Valid compounds: {{len(valid_idx)}} / {{len(df)}}")
'''
    elif feature_type == "rdkit_2d":
        code = '''# Generate RDKit 2D descriptors
from rdkit.Chem import Descriptors
from rdkit.ML.Descriptors import MoleculeDescriptors

# Get all descriptor names
descriptor_names = [x[0] for x in Descriptors._descList]
calc = MoleculeDescriptors.MolecularDescriptorCalculator(descriptor_names)

descriptors = []
valid_idx = []

for i, smi in enumerate(df[smiles_col]):
    mol = Chem.MolFromSmiles(smi)
    if mol is not None:
        try:
            desc = calc.CalcDescriptors(mol)
            descriptors.append(list(desc))
            valid_idx.append(i)
        except:
            pass

X = np.array(descriptors)
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)
y = df.iloc[valid_idx][label_col].values

print(f"Generated descriptors: {X.shape}")
print(f"Descriptor names: {len(descriptor_names)}")
'''
    else:
        code = f"# Feature type '{feature_type}' not implemented"

    return code


@skills.register("generate_model_code", "Generate model training code")
def generate_model_code(
    model_type: str = "random_forest",
    cv_folds: int = 5
) -> str:
    """
    Generate code for model training and evaluation.

    Args:
        model_type: Type of model
        cv_folds: Number of CV folds

    Returns:
        Python code string
    """
    code = f'''# Train and evaluate {model_type} model
from sklearn.model_selection import RepeatedStratifiedKFold, cross_validate
from sklearn.metrics import make_scorer, matthews_corrcoef

'''

    if model_type == "random_forest":
        code += '''from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=200, max_depth=10, class_weight='balanced', random_state=42, n_jobs=-1)
'''
    elif model_type == "xgboost":
        code += '''from xgboost import XGBClassifier
model = XGBClassifier(n_estimators=200, max_depth=5, learning_rate=0.1, random_state=42, n_jobs=-1)
'''
    elif model_type == "svm":
        code += '''from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

model = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(kernel='rbf', C=1.0, probability=True, class_weight='balanced', random_state=42))
])
'''
    else:
        code += f"# Model type '{model_type}' - add implementation\nmodel = None\n"

    code += f'''
# Cross-validation
cv = RepeatedStratifiedKFold(n_splits={cv_folds}, n_repeats=3, random_state=42)

scoring = {{
    'mcc': make_scorer(matthews_corrcoef),
    'roc_auc': 'roc_auc',
    'accuracy': 'accuracy'
}}

cv_results = cross_validate(model, X, y, cv=cv, scoring=scoring, n_jobs=-1)

print("Cross-validation results:")
print(f"  MCC: {{np.mean(cv_results['test_mcc']):.4f}} (+/- {{np.std(cv_results['test_mcc']):.4f}})")
print(f"  AUC: {{np.mean(cv_results['test_roc_auc']):.4f}} (+/- {{np.std(cv_results['test_roc_auc']):.4f}})")
print(f"  Accuracy: {{np.mean(cv_results['test_accuracy']):.4f}} (+/- {{np.std(cv_results['test_accuracy']):.4f}})")
'''

    return code
